name: Build macOS
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add aarch64-apple-darwin x86_64-apple-darwin
      - run: |
          cargo build --release -p manget_cli --target aarch64-apple-darwin
          cargo build --release -p manget_cli --target x86_64-apple-darwin
          lipo -create -output manget_cli \
            target/aarch64-apple-darwin/release/manget_cli \
            target/x86_64-apple-darwin/release/manget_cli
      - uses: actions/upload-artifact@v4
        with:
          name: manget_cli-macos
          path: manget_cli
